export const SENT_RESET_EMAIL: 'SENT_RESET_EMAIL' = 'SENT_RESET_EMAIL';
export const SENT_RESET_EMAIL_SUCCES: 'SENT_RESET_EMAIL_SUCCES' = 'SENT_RESET_EMAIL_SUCCES';
export const SENT_RESET_EMAIL_FAILED: 'SENT_RESET_EMAIL_FAILED' = 'SENT_RESET_EMAIL_FAILED';

export const SENT_RESET_PASSWORD: 'SENT_RESET_PASSWORD' = 'SENT_RESET_PASSWORD';
export const SENT_RESET_PASSWORD_SUCCES: 'SENT_RESET_PASSWORD_SUCCES' = 'SENT_RESET_PASSWORD_SUCCES';
export const SENT_RESET_PASSWORD_FAILED: 'SENT_RESET_PASSWORD_FAILED' = 'SENT_RESET_PASSWORD_FAILED';

export const SIGNIN: 'SIGNIN' = 'SIGNIN';
export const SIGNIN_SUCCES: 'SIGNIN_SUCCES' = 'SIGNIN_SUCCES';
export const SIGNIN_FAILED: 'SIGNIN_FAILED' = 'SIGNIN_FAILED';

export const REGISTER: 'REGISTER' = 'REGISTER';
export const REGISTER_SUCCES: 'REGISTER_SUCCES' = 'REGISTER_SUCCES';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCES: 'GET_USER_SUCCES' = 'GET_USER_SUCCES';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';

export const UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST' = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCES: 'UPDATE_USER_SUCCES' = 'UPDATE_USER_SUCCES';
export const UPDATE_USER_FAILED: 'UPDATE_USER_FAILED' = 'UPDATE_USER_FAILED';

export const EXIT_REQUEST: 'EXIT_REQUEST' = 'EXIT_REQUEST';
export const EXIT_SUCCES: 'EXIT_SUCCES' = 'EXIT_SUCCES';
export const EXIT_FAILED: 'EXIT_FAILED' = 'EXIT_FAILED';
