export const GET_INGRIDIENTS: 'GET_INGRIDIENTS' = 'GET_INGRIDIENTS';
export const GET_INGRIDIENTS_SUCCES: 'GET_INGRIDIENTS_SUCCES' = 'GET_INGRIDIENTS_SUCCES';
export const GET_INGRIDIENTS_FAILED: 'GET_INGRIDIENTS_FAILED' = 'GET_INGRIDIENTS_FAILED';
