export const GET_ORDER_NUMBER: 'GET_ORDER_NUMBER' = 'GET_ORDER_NUMBER';
export const GET_ORDER_NUMBER_SUCCES: 'GET_ORDER_NUMBER_SUCCES' = 'GET_ORDER_NUMBER_SUCCES';
export const GET_ORDER_NUMBER_FAILED: 'GET_ORDER_NUMBER_FAILED' = 'GET_ORDER_NUMBER_FAILED';
export const OPEN_ORDER_DETAILS: 'OPEN_ORDER_DETAILS' = 'OPEN_ORDER_DETAILS';
export const CLOSE_ORDER_DETAILS: 'CLOSE_ORDER_DETAILS' = 'CLOSE_ORDER_DETAILS';
